### ISSUE TITLE
create new mrm tasks for typical repos

### ISSUE THREAD

**Issue by simoneb** [nearform/mrm-preset-nearform#7]
- fastify plugin
- ...

**Comment by ramonmulia** [comment]
hey @radomird what more repositories could we create more tasks?

**Comment by radomird** [comment]
Recently we had an example of 2 repos that we built and are very similar:
- https://github.com/nearform/netsuite-slack-notifications
- https://github.com/nearform/github-bench-team

They both are Lambda functions and use AWS CDK for infra. I'm pretty sure these won't be the last ones that we are going to have, so it could be an idea to have a preset for these types of projects as well.
